[build]
  functions = "functions"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "true"
[build.production.environment]
  GENERATE_SOURCEMAP = "false"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200